### ISSUE TITLE
Same build, env, settings, nvim version but different looking theme

### ISSUE THREAD

**Issue by lukelarsen** [bluz71/vim-nightfly-colors#65] opened 2024-12-12 05:10 UTC
Thank you so much for this theme. I love it and have used it a lot. I'm setting up two computers using a .config repo I have set up on Github. When I run the two though I get slightly different looking themes. I've checked a lot of things to make sure they are the same. things like nvim versions and the like. Any idea what would cause these two computers to render the same color scheme differently? 

Desired Colors
<img width="879" alt="desired" src="https://github.com/user-attachments/assets/e332b10e-80ef-4d16-9df4-d443de1545c5" />

Not Desired Colors
<img width="869" alt="notDesired" src="https://github.com/user-attachments/assets/8a55ba91-3207-4c4a-9f75-65b6c92a43f0" />

**Comment by bluz71** [comment] 2024-12-12 06:03
Hello @lukelarsen,

I suspect LSP semantic highlighting is effecting the 2nd screenshot.

Move the mouse to `import` on both devices and run `:Inspect`.

It is likely you will see two different results, as in Tree-sitter for the first screen and maybe LSP Semantic Highlights on the second.

I may be able to tweak the theme equalize the highlights if my hypothesis is proved correct.

Let me know how it goes. I am pleased you like the theme.

Best regards.

**Comment by lukelarsen** [comment] 2024-12-12 15:34
It is just as you said! They have different results. I don't know enough about LSP to know what I did on the two computers to trigger the difference. I ran that command on both machine while on `import` and `name`. Here are the results of each. 

`import`

Desired
<img width="680" alt="Import-desired" src="https://github.com/user-attachments/assets/9a198174-7dd6-40e2-b64c-41cbd5bd5a2c" />

Not Desired
![Import-notDesired](https://github.com/user-attachments/assets/ff018d9b-8324-435d-8699-1aadf1237daf)


`name`

Desired
<img width="680" alt="Import-desired" src="https://github.com/user-attachments/assets/f813604d-d3ec-42bb-b81b-7fc1b62021ce" />

Not Desired
<img width="1044" alt="Name-notDesired" src="https://github.com/user-attachments/assets/0f3c7eaa-684f-43b2-8705-65f6963ca44f" />

If this is something that is fixable in the theme I'd love to send you some support or tip. Is there a way for me to do that?

**Comment by lukelarsen** [comment] 2024-12-13 01:12
This thread is interesting and might be related. 

https://github.com/NvChad/NvChad/issues/1907#issuecomment-1501756710

**Comment by bluz71** [comment] 2024-12-13 01:47
I am more confused now than before. The same capture groups are used in your _desired_ and _not desired_ cases. So my original hypothesis is ruled out.

I typed out your `details.tsx` file and my highlighting looks like your _desired_ cases. Your _desired_ is the correct base level styling.

I don't think LSP Semantic Tokens is your issue.

It feels like a plugin, or something, you are using may be redefining highlights?

Can you confirm you are running the same Tree-sitter commit on both your machines.

Also, please comment out all plugins except nightfly and Tree-sitter and test again. That also means commenting out LSP (temporarily).

This is a very strange issue, I have not seen this before.

Nonetheless, there will be an explanation and solution.

You will need to debug on the _not desired_ machine to figure out this strangeness.

**Comment by bluz71** [comment] 2024-12-13 01:55
This is especially strange:

![395226037-ff018d9b-8324-435d-8699-1aadf1237daf](https://github.com/user-attachments/assets/0937eeaa-74af-4245-8ddd-5bb9a0b7b395)

In my theme `@keyword.import` links to `Include` which in turn links to `PreProc` which itself links to `NightflyWatermelon`.

Instead in this case something has changed it to `Statement` which is very wrong.

Your job is to find out what is changing it to `Statement`.

**Comment by lukelarsen** [comment] 2024-12-13 05:57
I'm getting closer. When I remove the entire `after` folder there is no effect. 
I narrowed down the plugin that causes some change to Treesitter. 
Specifically the 
```highlight = { enabled = true, }``` 
line. 

If that is false some of the colors become correct. Like `import` but then different areas are broken.

What is really weird is that each computer seems to have the exact same setup. Maybe the parsers for treesitter are different on each computer. I'll look at that next.

**Comment by lukelarsen** [comment] 2024-12-13 06:02
I can use this to force the correct color.
`vim.api.nvim_set_hl(0, "@keyword.import.tsx", { link = "NightflyWatermelon" })`

**Comment by bluz71** [comment] 2024-12-13 06:35
> I can use this to force the correct color. `vim.api.nvim_set_hl(0, "@keyword.import.tsx", { link = "NightflyWatermelon" })`

That is not the ideal solution since you are just overriding what something is incorrectly changing.

Better to find the root cause.

> I'm getting closer. When I remove the entire `after` folder there is no effect.
> I narrowed down the plugin that causes some change to Treesitter.
> Specifically the
> `highlight = { enabled = true, }`
> line.

Which plugin? `nvim-treesitter`?

That line is correct for `nvim-treesitter`, you do want Tree-sitter highlighting. Don't change that.

I suggest completely deleting `nvim-treesitter` plugin from `~/.local/share/nvim/lazy/nvim-treesitter` and then making sure you are using the latest `nvim-treesitter` tagged release `0.9.3` in your `lazy` configuration, for example:

```lua
  {
    "nvim-treesitter/nvim-treesitter",
    tag = "v0.9.3",
    build = ":TSUpdate",
```

This should download the latest stable `nvim-treesitter` and then rebuild all your parsers.

**Comment by lukelarsen** [comment] 2024-12-13 17:16
Thanks for these suggestions. I tried them and even took the files from `.local/....` from the working computer and put them on the bad computer. No luck there either.

I did run `:Inspect` on some different parts of the code. This one is run on the bad computer while on the word `meta` on line 4.

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/909825e9-b932-4f8e-8e91-101b5f72db6e" />

This seems to be the LSP Semantic Tokens you were referring to before. Is that correct? The top of the output has the correct colors from Treesitter and it seems the Semantic Tokens area changes it to NightflyTurquoise.

**Comment by lukelarsen** [comment] 2024-12-13 22:06
For what it is worth... I can see the correct NightflyBlue color on `meta` for a split second and then it goes NightflyTurquoise.

**Comment by bluz71** [comment] 2024-12-13 23:51
> For what it is worth... I can see the correct NightflyBlue color on `meta` for a split second and then it goes NightflyTurquoise.

That is indicative of LSP semantic highlighting.

However, I wish to explore the color of the `import` keyword first which is not involving LSP as seen in this image:

![395384545-0937eeaa-74af-4245-8ddd-5bb9a0b7b395](https://github.com/user-attachments/assets/d0524767-75a4-4245-b676-fc57858caa92)

It should be `NightflyWatermelon` not `Statement`. Something related to your Tree-sitter is changing that.

Please comment out your LSP configuration and please move your [after/queries](https://github.com/lukelarsen/.config/tree/master/nvim/after/queries) out of the way.

When you do what color is `import`?

I wish to equalize Tree-sitter first **BEFORE** looking at LSP semantic highlighting.

**Comment by bluz71** [comment] 2024-12-14 00:21
Just looking more closely at your latest screenshot and the color of `import` is now correct:

<img width="1109" alt="395642974-909825e9-b932-4f8e-8e91-101b5f72db6e" src="https://github.com/user-attachments/assets/f73efaf3-9fb2-470c-b1ea-9830c6421d30" />

It used to be **incorrectly** be violet as seen in this image in your first post:

<img width="869" alt="395017384-8a55ba91-3207-4c4a-9f75-65b6c92a43f0" src="https://github.com/user-attachments/assets/3a836bad-06b4-4774-9cd6-214d403c8a3b" />

So, I must assume you found and fixed your Tree-sitter issue? Was it your [after/queries](https://github.com/lukelarsen/.config/tree/master/nvim/after/queries)?

**Comment by lukelarsen** [comment] 2024-12-14 04:01
The import isn't fixed. I had that one-liner in to override the color and force it back to Watermelon.

I've removed that
Removed the `after/queries`
Removed LSP
Removed Treesitter

With all those gone import is Watermelon and says this with :Inspect:
<img width="644" alt="image" src="https://github.com/user-attachments/assets/7b690c66-ec23-475c-9371-e368de01a30c" />
The typescriptImport part is different but it is the right color.

I then started to put the items back in. Just adding Treesitter back in caused the import to go back to the wrong color.

I then went through that file and nothing caused a change except this line:
```
highlight = {
  enable = true,
},
```
which we want in so I'm not sure what to do here.

**Comment by lukelarsen** [comment] 2024-12-14 04:16
Okay. I'm super confused but I'm not going to complain because `import` is working. I tried commenting things out again one by one and I expected to see that same screen shot in my comment just above but I didn't I saw this:

<img width="690" alt="image" src="https://github.com/user-attachments/assets/a6c3faab-c4be-4bd4-8d67-0a9dae55f595" />

`typescriptImport` from the above screenshot now has `@keyword.import.tsx` which is better right?

I then uncommented out the Treesitter things expecting the highlight enable setting to break it but it didn't.

My `lsp` and `after` stuff is still not included and the other colors in question are also working.

<img width="566" alt="image" src="https://github.com/user-attachments/assets/6686e574-b7b8-4b41-bb6a-4d89cfc4c985" />
<img width="655" alt="image" src="https://github.com/user-attachments/assets/d9749174-7d9f-41c8-b225-02ef37e698ef" />

**Comment by bluz71** [comment] 2024-12-14 04:38
When you disable Tree-sitter and LSP you will fall back for Vim style regex highlighting, hence `typescriptImport`.

I don't know why Tree-sitter is behaving so weirdly for you? Did you reinstall that with version `0.9.3` tag? Make sure that an old version of Neovim Tree-sitter is not lurking in your Neovim run path. Use `locate` to find any Tree-sitter installations.
 
To be honest, I don't think there is anything more I can do since I can not reproduce your inconsistency.

We do know the LSP semantic highlighting may be problematic for you, if so I suggest you disable LSP Semantic highlighting [as documented here](https://gist.github.com/swarn/fb37d9eefe1bc616c2a7e476c0bc0316#disable-semantic-highlighting):

```lua
lspconfig.ts_ls.setup {
  on_init = function(client, _)
    client.server_capabilities.semanticTokensProvider = nil
  end,
  on_attach = ...,
  settings = ...,
}
```

That is if Tree-sitter highlighting works better for you; but strangely it may be worse than LSP (for you). Note, that should not be the case.

I will close this issue since I believe you will need to continue your own exploration. I don't know what else to do.

I do not believe there are any issues at the colorscheme level.

Sorry I could not be of more help.

Best regards.

**Closed by bluz71** 2024-12-14 04:38 UTC

**Comment by lukelarsen** [comment] 2024-12-14 04:46
Thanks for all your help. 
I did install that version of Treesitter. I'll look for any other copies though.  
I'll poke around with my LSP configuration. Thanks again!

**Comment by bluz71** [comment] 2024-12-14 05:24
It should be a solvable problem.

If I were you I would disable LSP Semantic Tokens UNTIL you find out why your Tree-sitter highlights are broken on one of your two machines.

Good news, you have two devices to compare, one working, one not; hence with enough debugging you should get to the root of the Tree-sitter issue.

Best regards.
